### ISSUE TITLE
 NUMBER(oracle) -> int(c#)

### ISSUE THREAD

**Issue by huseyinorer** [olsh/datagrip-poco-generator#5]
I tried to add NUMBER(oracle) to typemapping dictionary but it not working. Is there any way for oracle NUMBER types ?

**Comment by olsh** [comment]
Hi @huseyinorer 
I don't have an Oracle instance to test it, but this should be pretty simple.
You need to add Oracle type here
https://github.com/olsh/datagrip-poco-generator/blob/39a9e56e559d063edaf46d82e70e9c2214add70b/Generate%20POCO.groovy#L10

I'll test it if I manage to set up a test oracle instance.

**Comment by huseyinorer** [comment]
Sorry my bad .I solved. I 've used uppercase. 
 This is working now.
`(~/(?i)^number/)                                 : "int",`

**Comment by olsh** [comment]
Thanks, I added the mapping to the scripts.
